java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

servicebus:
  enabled: true
  releaseNameOverride: ${SERVICE_NAME}-asb
  resourceGroup: et-aat
  sbNamespace: et
  setup:
    topics:
      - name: ccd-case-events
        subscriptionNeeded: yes
        requiresSession: true

wa:
  enabled: true
  wa-case-event-handler:
    java:
      secrets:
        AZURE_SERVICE_BUS_CONNECTION_STRING:
          secretRef: ccd-shared-servicebus-connection-string
          key: connectionString
      environment:
        CCD_URL: http://{{ .Release.Name }}-ccd-data-store-api
        CCD_SEARCH_URL: http://{{ .Release.Name }}-ccd-data-store-api
        ROLE_ASSIGNMENT_URL: http://{{ .Release.Name }}-am-role-assignment-service
        AZURE_SERVICE_BUS_TOPIC_NAME: ${SERVICE_NAME}-asb-ccd-case-events
        AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-asb-ccd-case-events
        AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: ${SERVICE_NAME}-asb-ccd-case-events

ccd-message-publisher:
  java:
    ingressHost: ccd-message-publisher-${SERVICE_FQDN}
    releaseNameOverride: ${SERVICE_NAME}-ccd-message-publisher
    keyVaults:
      ccd:
        secrets:
          - name: AppInsightsInstrumentationKey
            alias: azure.application-insights.instrumentation-key
    environment:
      DATA_STORE_DB_HOST: "{{ .Release.Name }}-postgresql"
      DATA_STORE_DB_NAME: data-store
      DATA_STORE_DB_USERNAME: hmcts
      DATA_STORE_DB_PASSWORD: hmcts
      DATA_STORE_DB_OPTIONS: "?stringtype=unspecified"
      CCD_CASE_EVENTS_DESTINATION: ${SERVICE_NAME}-asb-ccd-case-events
    secrets:
      SERVICE_BUS_CONNECTION_STRING:
        secretRef: ccd-shared-servicebus-connection-string
        key: connectionString
